name: Test Minimal Adapter

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-minimal-adapter:
    name: Test the minimal adapter example
    uses: ./.github/workflows/test-sdk-action.yml
    with:
      adapter-dockerfile: "Dockerfile"
      adapter-context: "examples/minimal_adapter"
      test-harness-version: "latest"
